---
- hosts: master
  gather_facts: False
  tasks:
    - name: edit kube-proxy daemonset (workaround for .....)
      shell:  >
        kubectl -n kube-system get ds -l 'component=kube-proxy' -o json | 
          jq '.items[0].spec.template.spec.containers[0].command 
          |= .+ ["--conntrack-max-per-core=0"]' | 
          kubectl apply -f - && 
          kubectl -n kube-system delete pods -l 'component=kube-proxy'
